[package]
name = "aper"
version = "0.4.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
dashmap = "6.0.1"
serde = { version = "1.0.204", features = ["derive"] }
aper-derive = {path = "./aper-derive"}
chrono = { version = "0.4.38", features = ["serde"] }
