[package]
name = "aper-book"
version = "0.2.2"
authors = ["Paul Butler <paulgb@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
aper = { path = "../../aper" }
doc-comment = "0.3.3"
serde = { version = "1.0.123", features = ["derive"] }

