[package]
name = "aper-yew"
version = "0.1.0"
authors = ["Paul Butler <paulgb@gmail.com>"]
edition = "2018"
repository = "https://github.com/drifting-in-space/aper"

[dependencies]
aper = { path="../aper" }
aper-jamsocket = { path="../aper-jamsocket" }
bincode = "1.3.3"
chrono = { version = "0.4.19", features = ["serde", "wasmbind"] }
console_error_panic_hook = "0.1.7"
js-sys = "0.3.55"
serde = "1.0.126"
serde_json = "1.0.74"
wasm-bindgen = "0.2.78"
web-sys = "0.3.55"
yew = "0.18.0"
