[package]
name = "aper-yew"
version = "0.1.0"
authors = ["Paul Butler <paulgb@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aper = {path="../aper"}
chrono = { version = "0.4.19", features = ["serde", "wasmbind"] }
yew = "0.17.4"
