[package]
name = "drop-four-common"
version = "0.1.0"
edition = "2018"

[dependencies]
aper = {path="../../../aper"}
aper-stateroom = {path="../../../aper-stateroom"}
serde = { version = "1.0.127", features = ["derive"] }

[dev-dependencies]
chrono = "0.4.19"
