[package]
name = "aper_derive"
version = "0.0.2"
authors = ["Paul Butler <paulgb@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inflections = "1.1.1"
proc-macro2 = "1.0.24"
quote = "1.0.9"
syn = { version = "1.0.60", features = ["full"] }
