[package]
name = "timer-service"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aper = { path="../../../aper" }
aper-stateroom = { version="0.2.4" }
stateroom-wasm = { version="0.2.4" }
timer-common = { path="../common" }
