[package]
name = "aper-jamsocket"
version = "0.1.0"
edition = "2018"

[dependencies]
jamsocket = { version="0.1.3", path="../../jamsocket/jamsocket" }
aper = { path = "../aper" }
serde = "1.0.126"
serde_json = "1.0.59"
bincode = "1.3.3"
chrono = "0.4.19"
log = "0.4.14"
