[package]
name = "aper-jamsocket"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jamsocket = { git = "https://github.com/jamsocket/jamsocket", version="0.1.0" }
aper = {path = "../aper"}
serde = "1.0.126"
serde_json = "1.0.59"
bincode = "1.3.3"
chrono = "0.4.19"
log = "0.4.14"
