[package]
name = "aper-serve"
version = "0.1.0"
edition = "2018"

[dependencies]
aper = {path = "../aper"}
aper-jamsocket = {path = "../aper-jamsocket"}
env_logger = "0.9.0"
jamsocket-server = { version="0.1.3", path="../../jamsocket/jamsocket-server" }
log = "0.4.14"
