[package]
name = "aper-serve"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aper = {path = "../aper"}
aper-jamsocket = {path = "../aper-jamsocket"}
env_logger = "0.9.0"
jamsocket-server = { git = "https://github.com/jamsocket/jamsocket", version="0.1.0" }
log = "0.4.14"
