[package]
name = "aper-stateroom"
version = "0.1.5"
edition = "2018"
repository = "https://github.com/drifting-in-space/aper"

[dependencies]
stateroom = { version="0.2.2", features=["serde"] }
aper = { version="0.1.4", path = "../aper" }
serde = "1.0.126"
serde_json = "1.0.75"
bincode = "1.3.3"
log = "0.4.17"
chrono = { version = "0.4.20", features = ["serde"] }
