name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install Nightly
      run: rustup toolchain install nightly
    - name: Build docs
      run: RUSTDOCFLAGS="--enable-index-page -Zunstable-options" cargo +nightly doc -p aper -p aper-yew -p aper-actix --no-deps
    - name: Install mdbook
      run: cargo install mdbook
    - name: Build book
      run: mdbook build book
    - name: Move docs
      run: mv target/doc book/book/doc
    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages
        #folder: target/doc
        folder: book/book
