[package]
name = "drop-four-service"
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
aper-stateroom = {path="../../../aper-stateroom"}
stateroom-wasm = { version="0.4.0" }
drop-four-common = { path="../common" }
